/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.capgi;

import org.junit.Test;

public class StateAnalyserCensusTest {
	public static final String STATE_CENSUS_DATA_FILE = "F:\\Capgemini_training1\\java_eclipse\\IndiaStateCensusAnalyser"
			+ "\\IndiaStateCensusData.csv";

	@Test
	public void testSomeLibraryMethod() {
	}
}
